spring.profiles.active: dev

server:
 port: 8080
spring:
 kafka:
  bootstrap-servers: trabalho-receitas.servicebus.windows.net:9093
  properties:
   sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://trabalho-receitas.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=lB3cAFoIuKjkKoyVLI48YQvqNj8n6U5oo+AEhLeClIg=";
   sasl.mechanism: PLAIN
   security.protocol: SASL_SSL
  consumer:
   group-id: $Default
   auto-offset-reset: earliest
   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
 
topics:
  subscriber: app-receitas
  
spring.mail:
 host: mail.smtp2go.com
 port: 2525
 username: sga.pucminas.br
 password: nIHaSNAZSfZIAjwp
 properties:
  mail:
   smtp:
    auth: true
    socketFactory:
     port: 465
     class: javax.net.ssl.SSLSocketFactory
 
 