spring.profiles.active: dev

server:
 port: 8080
spring:
 kafka:
  bootstrap-servers: "link-do-broker"
  properties:
   sasl.jaas.config: "senha-de-acesso"
   sasl.mechanism: PLAIN
   security.protocol: SASL_SSL
  consumer:
   group-id: $Default
   auto-offset-reset: earliest
   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
 
topics:
  subscriber: "topico"
  
spring.mail:
 host: 
 port: 
 username: "username"
 password: "senha-smtp"
 properties:
  mail:
   smtp:
    auth: true
    socketFactory:
     port: 465
     class: javax.net.ssl.SSLSocketFactory
 
 